import { mock } from "bun:test";

// Mock virtual unplugin-icons modules for Bun test runner without requiring React at root
const DummyIcon = (props: any) => null;

const iconNames = [
  "boxicons/search",
  "boxicons/dashboard-filled",
  "solar/cart-4-bold",
  "mingcute/time-fill",
  "solar/settings-bold",
  "icon-park-solid/setting",
  "cuida/sidebar-collapse-outline",
  "cuida/sidebar-expand-outline",
  "solar/sun-bold",
  "solar/moon-bold",
  "material-symbols/computer",
  "lucide/chevron-down",
  "griddy-icons/chevron-up-filled",
  "mingcute/left-fill",
  "mingcute/right-fill",
  "solar/arrow-left-linear",
  "solar/alt-arrow-right-linear",
  "solar/arrow-right-linear",
  "solar/arrow-up-bold",
  "solar/home-2-bold",
  "solar/compass-bold",
  "solar/file-remove-bold",
  "boxicons/check",
  "lucide/x",
  "solar/close-circle-linear",
  "tabler/plus-filled",
  "solar/add-circle-bold",
  "lets-icons/edit-fill",
  "solar/copy-bold",
  "solar/trash-bin-trash-bold",
  "mingcute/delete-fill",
  "mingcute/more-4-line",
  "mingcute/column-fill",
  "solar/eye-bold",
  "solar/eye-closed-bold",
  "bxs/hide",
  "ic/round-menu",
  "solar/command-bold",
  "solar/shield-bold",
  "solar/download-bold",
  "material-symbols/tab-group-rounded",
  "lucide/inbox",
  "solar/logout-linear",
  "ep/success-filled",
  "carbon/close-filled",
  "bxs/error",
  "lucide/triangle-alert",
  "lucide/circle-alert",
  "lucide/info",
  "mdi/error",
  "lets-icons/view-fill",
  "lucide/maximize-2",
  "lucide/minimize-2",
  "solar/box-bold",
  "solar/clipboard-list-bold",
  "solar/laptop-bold",
  "solar/smartphone-bold",
  "solar/key-bold",
  "solar/qr-code-bold",
  "solar/shield-check-bold",
  "logos/google-icon",
  "logos/github-icon",
  "logos/apple",
  "solar/user-bold",
  "solar/users-group-two-rounded-bold",
  "basil/refresh-solid",
  "lucide/upload-cloud",
  "lucide/link-2",
  "lucide/file-text",
  "akar-icons/cloud-upload",
  "humbleicons/spinner-earring",
];

for (const name of iconNames) {
  mock.module(`~icons/${name}`, () => ({
    default: DummyIcon,
  }));
}
