import swaggerJSDoc from "swagger-jsdoc";
import { env } from "./env";

const options: swaggerJSDoc.Options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Admin Template API Docs",
      version: "1.0.0",
      description:
        "Interactive OpenAPI documentation and API explorer for the Admin Template backend.",
      contact: {
        name: "API Support",
      },
    },
    servers: [
      {
        url: env.API_BASE_URL + env.API_PREFIX,
        description: "Development Server",
      },
    ],
    components: {
      securitySchemes: {
        cookieAuth: {
          type: "apiKey",
          in: "cookie",
          name: "better-auth.session_token",
          description: "Better Auth session cookie",
        },
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description: "Bearer Token authentication",
        },
      },
      schemas: {
        ApiResponse: {
          type: "object",
          properties: {
            success: { type: "boolean", example: true },
            data: { type: "object", nullable: true },
            message: { type: "string", nullable: true },
            error: { type: "string", nullable: true },
          },
        },
        SignInEmailPayload: {
          type: "object",
          required: ["email", "password"],
          properties: {
            email: {
              type: "string",
              format: "email",
              example: "admin@admin.com",
            },
            password: {
              type: "string",
              format: "password",
              example: "Admin@123456",
            },

            rememberMe: {
              type: "boolean",
              example: true,
            },
          },
        },
        UpdateUserPayload: {
          type: "object",
          properties: {
            name: {
              type: "string",
              example: "Leon Alvarez",
            },
            image: {
              type: "string",
              nullable: true,
              example: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
            },
          },
        },
        ChangePasswordPayload: {
          type: "object",
          required: ["currentPassword", "newPassword"],
          properties: {
            currentPassword: {
              type: "string",
              format: "password",
              example: "CurrentPassword@123",
            },
            newPassword: {
              type: "string",
              format: "password",
              example: "NewSecurePassword@456",
            },
          },
        },
        EnableTwoFactorPayload: {
          type: "object",
          required: ["password"],
          properties: {
            password: {
              type: "string",
              format: "password",
              description: "Current password of the authenticated user.",
              example: "Admin@123456",
            },
            method: {
              type: "string",
              enum: ["totp", "otp"],
              default: "totp",
              description: "Two-factor method to enable (defaults to totp).",
              example: "totp",
            },
            issuer: {
              type: "string",
              description: "Custom issuer name for the TOTP URI.",
              example: "Zero Admin",
            },
          },
        },
        EnableTwoFactorResponse: {
          type: "object",
          properties: {
            method: {
              type: "string",
              enum: ["totp", "otp"],
              example: "totp",
            },
            totpURI: {
              type: "string",
              nullable: true,
              description: "TOTP URI for generating QR code in authenticator apps.",
              example:
                "otpauth://totp/Zero%20Admin:admin@admin.com?secret=JBSWY3DPEHPK3PXP&issuer=Zero%20Admin",
            },
            backupCodes: {
              type: "array",
              items: { type: "string" },
              nullable: true,
              description: "List of one-time emergency backup recovery codes.",
              example: ["a1b2c3d4", "e5f6g7h8", "i9j0k1l2", "m3n4o5p6"],
            },
          },
        },
        VerifyTotpPayload: {
          type: "object",
          required: ["code"],
          properties: {
            code: {
              type: "string",
              description: "6-digit TOTP authentication code generated by authenticator app.",
              example: "123456",
            },
          },
        },
        DisableTwoFactorPayload: {
          type: "object",
          required: ["password"],
          properties: {
            password: {
              type: "string",
              format: "password",
              description: "Current password of the authenticated user to verify deactivation.",
              example: "Admin@123456",
            },
          },
        },
        VerifyBackupCodePayload: {
          type: "object",
          required: ["code"],
          properties: {
            code: {
              type: "string",
              description: "Emergency single-use backup recovery code.",
              example: "a1b2c3d4",
            },
          },
        },
        Product: {
          type: "object",
          properties: {
            id: { type: "integer", example: 1 },
            name: {
              type: "string",
              example: "Wireless Noise-Canceling Headphones",
            },
            description: {
              type: "string",
              nullable: true,
              example: "Premium audio experience with active noise control",
            },
            price: { type: "number", example: 199.99 },
            stock: { type: "integer", example: 45 },
            slug: {
              type: "string",
              example: "wireless-noise-canceling-headphones",
            },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        CreateProductPayload: {
          type: "object",
          required: ["name", "price", "stock"],
          properties: {
            name: { type: "string", example: "Ergonomic Mechanical Keyboard" },
            description: {
              type: "string",
              example: "Custom hot-swappable RGB keyboard",
            },
            price: { type: "number", example: 129.5 },
            stock: { type: "integer", example: 20 },
            slug: { type: "string", example: "product-1" },
          },
        },
        UpdateProductPayload: {
          type: "object",
          properties: {
            name: {
              type: "string",
              example: "Ergonomic Mechanical Keyboard v2",
            },
            description: {
              type: "string",
              example: "Updated layout with wireless BT 5.2",
            },
            price: { type: "number", example: 149.99 },
            stock: { type: "integer", example: 35 },
          },
        },
      },
    },
  },
  apis: ["./src/core/route-handler/*.ts", "./src/modules/**/*.ts"],
};

export const openApiSpec = swaggerJSDoc(options);
